### ISSUE TITLE
可以根据teleport开发socket.io的插件吗？

### ISSUE THREAD

**Issue by AlexStacker** [henrylee2cn/teleport#13]
我们的项目之前是根据socket.io开发的实时推送服务，最近用户猛增，导致服务器转发消息延迟很大，想用go重写服务端，但是客户端还用socket.io兼容，估计只能适配socket.io的协议来改服务端这一块，不知道意义可大，plugin的方式可不可行。

**Comment by henrylee2cn** [comment]
兼容socket.io的协议，你可以在服务端使用teleport自定义实现相应的socket.Proto接口

**Comment by AlexStacker** [comment]
先谢啦，晚上回去研究一下怎么实现。

**Comment by 23233** [comment]
@AlexStacker  研究出来了吗？

**Comment by henrylee2cn** [comment]
@23233 已经有扩展包实现了 https://github.com/henrylee2cn/teleport/tree/v5/mixer/websocket

**Comment by Natuka** [comment]
请教下，基于h5 websocket客户端有范例吗？

**Comment by henrylee2cn** [comment]
猜测是前后两次 receiveData.seq 相同

**Comment by Natuka** [comment]
感谢回复，
receiveData.seq，这边我是根据后端推送过来的数据，然后作为发送数据作为测试用，
我这边把数据修改为相同和不同，得到的效果是相同的，看源码是通过seq去匹配后端的注册路由。

**Comment by henrylee2cn** [comment]
seq必须是唯一ID

**Comment by Natuka** [comment]
好的，我在试试看。

**Comment by Natuka** [comment]
我这边尝试了下
```json
{
  "seq": 1,
  "mtype": 2,
  "uri": "/pong/receive",
  "serviceMethod": "/pong/receive",
  "meta": "",
  "body_codec": 106,
  "body": "5",
  "xfer_pipe": []
}
```
中的`mtype` 类型是TypeReply，TypePush，TypeCall，对于客户端来说，貌似调用的是TypeReply,但使用后发现是go 客户端调用的，直接用h5的websocket调用时，提示`[WARN] not found call cmd:`,后又尝试了使用TypeCall，这个提示`read message: invalid character 'x' after top-level valuesend:`, 现在对h5 websocket发送给服务端和服务端接收处理消息，目前无法正常收到消息，可能是我这边使用方式出现了问题，所以有`h5的范例`可供参考下？

**Comment by henrylee2cn** [comment]
H5或者go协议都是相同的，请求的key怎么是驼峰的？你对比这个看看：
![image](https://user-images.githubusercontent.com/10174178/88159848-75875c80-cc40-11ea-965f-f3f4d1f687b2.png)

https://github.com/henrylee2cn/erpc/tree/master/mixer/websocket

**Comment by henrylee2cn** [comment]
格式 `{"seq":%d,"mtype":%d,"serviceMethod":%q,"meta":%q,"bodyCodec":%d,"body":"%s","xferPipe":%s}`

**Comment by Natuka** [comment]
感谢回复，
这个我之前有看过范例，不过传参时，最早也是采用下划线的形式，但是打印源码之后，发现解析出来`body_codec`的值是0，因为json解析时我记得是需要在结构体后面做标记定义。

现在已经通了，不过我不解的是，body里面必须要json字符串？我发现传入的参数为
```javascirpt
var sendData = {
              seq: receiveData ? receiveData.seq : 0,
              mtype: 1,
              uri: "/other/receive",
              serviceMethod: "/other/receive",
              // meta: "",
              bodyCodec: 106,
              body: "5xxxxx",
              xferPipe: [],
            };
```
时，后端接收后提示`invalid character 'x' after top-level valuesend:`, 然后我这边去掉之后就正常了。

**Comment by Natuka** [comment]
还有就是`body_codec` 这个值必须固定是`106`吗？如果不是，我这边要如何传参？

**Comment by henrylee2cn** [comment]
对，body是json的，bodyCodec应该是 'j' ，没错次是 106

**Comment by Natuka** [comment]
好的，感谢。
