### ISSUE TITLE
请问如何才能关闭控制台的打印信息？

### ISSUE THREAD

**Issue by go-xworkflow** [henrylee2cn/teleport#16]
感谢作者的开源项目
请问如何才能关闭控制台的打印信息？

**Comment by jkingben** [comment]
tp.SetLoggerLevel("INFO") 调高点
tp.PeerConfig里的PrintDetail 设成 false

**Comment by go-xworkflow** [comment]
@jkingben 我就是将loggerlevel调高了，而且设置了tp.PeerConfig里的PrintDetail为false，但是还是会在控制台打印出这样的日志
[2018/05/28 15:59:28.444] [PRIN] The current process PID: 8940 <github.com/henrylee2cn/teleport/common.go:292>
[2018/05/28 15:59:28.451] [PRIN] register PULL handler: /math/add <github.com/henrylee2cn/teleport/router.go:284>
[2018/05/28 15:59:28.467] [PRIN] listen and serve (network:tcp, addr:[::]:9090) <github.com/henrylee2cn/teleport/peer.go:323>

我不知道如何屏蔽[PRIN]分类的打印信息，好奇怪啊。

代码就是这么写的

~~~
func main() {
	tp.SetLoggerLevel("ERROR")
	srv := tp.NewPeer(tp.PeerConfig{
		CountTime:     true,
		ListenAddress: ":9090",
		PrintDetail:   false,
	})

	srv.RoutePull(new(math))
	srv.ListenAndServe()
}
~~~

**Comment by jkingben** [comment]
const (
	PRINT Level = iota
	CRITICAL
	ERROR
	WARNING
	NOTICE
	INFO
	DEBUG
	TRACE
)
log级别是这么定义的，判断是这样的：level <= l.GetLevel(module)，前面是传进来的级别，后面是设置的级别
所以RPINT默认都是会打出来

**Comment by go-xworkflow** [comment]
唉，这样太不友好了，有时候只是想写点命令行的程序，但是在命令行的界面会打印这些print级别的信息，导致我的命令行程序，交互界面很差。

**Comment by go-xworkflow** [comment]
@jkingben 你试过使用其他的日志包么？我还没有把其他日志包与这个库集成成功过，那个setlogger好像有点难用，你有成功经验可以分享么？

**Comment by jkingben** [comment]
这log我觉得不错，你看log文档说明，支持不同级别定义写入到不同日志里。熟悉就好，你要觉得这PRINT不爽，那就把PRINT放到最后面

**Comment by go-xworkflow** [comment]
@jkingben 那我就要改他源码了，我本来是想写个命令行交互的小程序，结果交互界面老是被这个PRINT级别的日志弄的面目全非。他这个log怎么配置把日志写到文件里？我好像没有看到相关内容。

**Comment by jkingben** [comment]
你看他go-logging源码有console，memory，file，三种类型。他框架用的是console，如果你用nohup等管道重定向命令，不在意在一个文件里，那就用console就行

**Comment by go-xworkflow** [comment]
go-logging源码有console，memory，file三种类型，但是teleport好像又重新封装了一下，我试了下，没试成功。我其实就是写了一个命令行有交互界面的小程序，不能是nohup执行的，主要就是他这个日志弄的我命令行的交互界面面目全非了，另外我还希望日志能输出到日志文件，最好是能有直接配置的那种。不过这个库好像目前不提供这些功能，我目前只好打算还是用标准库来写了。那个setlogger也好像挺难用的，我试图使用其他日志库，但是好像不好写，也可能是我用法不对，对go的这些包还是不够熟练。现在只能继续学习中了， @jkingben 请问，你用这个包，日志输出到日志文件是怎么写的？

**Comment by jkingben** [comment]
go-logging里有个examples目录，自己运行下这目录下的代码
把 backend1Leveled.SetLevel(logging.TRACE, "") TRACE 改成ERROR，加深点理解。需不需要再使用他提供的log，你可以自己决定啊，他也是封装了一层而已

**Comment by go-xworkflow** [comment]
go-logging我会用的，反而是他在teleport里的这个封装我不会用了。另外我还想用自己熟悉的日志包呢，毕竟go-logging，好像没有切割日志，循环等功能。 @henrylee2cn 是否可以改进一下teleport的日志模块，我希望能用自己熟悉的日志包，但是那个setlogger好像不好用，或者 @henrylee2cn 能否给一个使用setlogger的例子。还有这个PRINT级别的日志是默认打印的，在开发类似命令行交互界面的小程序的时候很不友好，能否考虑下优化，我本来是想加一个NONE级别的，不过这样又好像不好，我日志文件还想打印点其他信息呢。golang初学者，希望得到 @henrylee2cn 的指导。最后感谢 @jkingben 的耐心答复，我目前的困惑其实是不会用teleport的这个日志模块，go-logging反而会用，但是我又觉得go-logging的功能有点弱，不能切割日志们不能按时间循环输出等

**Comment by henrylee2cn** [comment]
Now, the go-logging package is supported `OFF` level.

```sh
go get -u github.com/henrylee2cn/go-logging
```

**Comment by henrylee2cn** [comment]
The go-logging is simple but great. You can customize `backend` in accordance with the needs, such as cutting logs.
