### ISSUE TITLE
Server端调用了Close，监听还是存在，如何退出服务器？

### ISSUE THREAD

**Issue by jkingben** [henrylee2cn/teleport#17]
例子是simple里的。

服务器端：
在ListenAndServe前加了个定时器，2秒后关闭服务器
	go func() {
		time.Sleep(2 * time.Second)
		srv.Close()
	}()
	srv.ListenAndServe()
	fmt.Println("exit.............")

客户端：
	在 cli.Dial(":9090") 后也加了个定时器，3秒后重连
	go func() {
		time.Sleep(3 *time.Second)
		cli.Dial(":9090")
	}()

服务器2秒后执行关闭，并没有退出监听，后面打印也没继续，3秒后客户端还是继续连接成功
看代码还是阻塞在Accept那，这如何退出服务器？

**Comment by henrylee2cn** [comment]
Thanks for your issue, I'm allready fix the bug: https://github.com/henrylee2cn/teleport/commit/da33a65473fc98908a3cdf9e6414a2c7b36654a3
