### ISSUE TITLE
AsyncPull 怎样从PullCmd 中获取session 信息?

### ISSUE THREAD

**Issue by yangbinnnn** [henrylee2cn/teleport#19]
有一组peer，对这组peer 发起一个异步的请求，并使用pingCmdChan 接受所有peer 返回的结果，问题是如何从返回的PullCmd 中获取session (即怎么确认结果是哪个peer 返回的)？
(ps: 是不是AsyncPull 不能这么用)

部分代码如下:
```
	pingCmdChan := make(chan tp.PullCmd, batch)
	for _, peer := range hub.others {
                ......
		peer.sess.AsyncPull(
			"/peer/ping",
			"ping",
			new(string),
			pingCmdChan,
		)
	}
        ......
	for pingCmd := range pingCmdChan {
		result, rerr := pingCmd.Reply()
                sess = pingCmd.XXXXX // ?
        }
```

**Comment by henrylee2cn** [comment]
pingCmd 新增加了 `TracePeer()` 和 `TraceSession()` 两个方法用于溯源。

你当前使用的是v3版本，可以在teleport目录通过 `git pull&&git checkout v3&&git pull` 来更新你的代码。

同时，也推荐你切换到体验最新的v4版本：`git pull&&git checkout v4&&git pull`

**Comment by yangbinnnn** [comment]
谢谢，很好用！
