### ISSUE TITLE
服务端如何主动关闭一个连接？

### ISSUE THREAD

**Issue by jkingben** [henrylee2cn/teleport#22]
push = tp.PushCtx
err := push.Session().Close()

发现一点效果都没有，服务器并不能这样主动关闭客户端的连接。

**Comment by jkingben** [comment]
调用Health()返回的结果是 true，status应该是statusOk，不可能是statusPassiveClosed

这个status能不能暴露个方法出来被调用下

**Comment by henrylee2cn** [comment]
不能在handler中同步关闭session，会造成死锁。
需要在协程中关闭：
	push = tp.PushCtx
	go func(){
		err := push.Session().Close()
	}()

或者 
go func(){
sess,ok:=peer.GetSession(id)
sess.Close()
}()

**Comment by jkingben** [comment]
好的，感谢。
