### ISSUE TITLE
自定义协议如何支持像Thrift这样的RPC协议

### ISSUE THREAD

**Issue by xzy256** [henrylee2cn/teleport#36]
想定制自己的协议让其支持类似thrift这样的RPC协议，看了您的git上的说明不是很明白，求赐教。

**Comment by henrylee2cn** [comment]
参考 https://github.com/henrylee2cn/teleport/tree/v4/proto/jsonproto 实现你自己协议

**Comment by xzy256** [comment]
首先感谢百忙之中抽空看我的问题。研究了`jsonproto`这个例子，server和client端，传入了实现`Version、unpack、pack`三个接口方法的`jsonproto.NewJsonProtoFunc`实例，这倒好理解，但对于thrift协议，它使用本身的库去创建socket通信，类似代码:
<pre>
transportFactory := thrift.NewTFramedTransportFactory(thrift.NewTTransportFactory)
transport, _ := thrift.NewTSocket(net.JoinHostPort("127.0.0.1", "9090"))
useTransport := transportFactory.GetTransport(transport) 
</pre>
做定制时，如何改动代码，以实现thrift RPC的支持，希望大牛能指点一二。
<pre>
// Server
srv := tp.NewPeer(tp.PeerConfig{ListenPort: 9090})
srv.RouteCall(new(Home))
go srv.ListenAndServe(jsonproto.NewJsonProtoFunc)
time.Sleep(1e9)

// Client
cli := tp.NewPeer(tp.PeerConfig{})
cli.RoutePush(new(Push))
sess, err := cli.Dial(":9090", jsonproto.NewJsonProtoFunc)
</pre>

**Comment by henrylee2cn** [comment]
已经在v5分支实现了thrift协议：
https://github.com/henrylee2cn/teleport/commit/41fb685f4d2a53d8b59a7b78049e23f19eed5da6

**Comment by henrylee2cn** [comment]
已经在v5分支实现了thrift协议：
https://github.com/henrylee2cn/teleport/tree/v5/proto/thriftproto
