### ISSUE TITLE
 所谓的支持自定义协议，是基于Message结构体的定制协议吗，可不可以不基于Message呢？

### ISSUE THREAD

**Issue by zhaoyangwyyx** [henrylee2cn/teleport#37]

**Comment by henrylee2cn** [comment]
可以在自己定义的Proto接口中扩展各种协议格式，只要保证能向tp提供必要的message字段就可以，必要字段有：
- seq
- url
- meta
- body
- bodycodec（如果固定一个编码，也能省去）
