### ISSUE TITLE
支持断线重连吗？还是需要手动实现？

### ISSUE THREAD

**Issue by dean2021** [henrylee2cn/teleport#39]
支持断线重连吗？还是需要手动实现？

**Comment by henrylee2cn** [comment]
支持，在拨号的peer上，配置以下两个参数：
![image](https://user-images.githubusercontent.com/10174178/50745832-36183b80-1267-11e9-8f0f-14a63d4134aa.png)

**Comment by dean2021** [comment]
> 支持，在拨号的peer上，配置以下两个参数：
> ![image](https://user-images.githubusercontent.com/10174178/50745832-36183b80-1267-11e9-8f0f-14a63d4134aa.png)

建议写个teleport的使用文档，这样方便使用者能够快速入门，避免采坑

**Comment by yangwenmai** [comment]
> > 支持，在拨号的peer上，配置以下两个参数：
> > ![image](https://user-images.githubusercontent.com/10174178/50745832-36183b80-1267-11e9-8f0f-14a63d4134aa.png)
> 
> 建议写个teleport的使用文档，这样方便使用者能够快速入门，避免采坑

你现在知道用法了，我建议你可以给这个用法写一个使用文档，提一个PR。
