### ISSUE TITLE
是否支持filter chain？类似netty或mina

### ISSUE THREAD

**Issue by leenux** [henrylee2cn/teleport#4]
是否支持filter chain？类似netty或mina

**Comment by henrylee2cn** [comment]
支持plugin hooks，有很多挂钩可选

**Comment by 007shaoye** [comment]
虽然看不懂，但感觉很高大上的样子!  ^_^
问下可不可以实现类似于saltstack这种c/s模式，保持连接，交互执行命令？初学者，求指教.

**Comment by henrylee2cn** [comment]
嗯嗯，支持保持连接，交互执行命令的
