### ISSUE TITLE
请问作为Server时，如何设置新连接建立以及接收到client消息的回调？

### ISSUE THREAD

**Issue by johntaiii** [henrylee2cn/teleport#40]
翻了一遍Demo以及Peer、Session相关的代码，没找到相关的函数，麻烦指导下，谢谢。

**Comment by henrylee2cn** [comment]
实现一个 PostAcceptPlugin 插件，它在服务端接收新连接时被调用：
https://github.com/henrylee2cn/teleport/blob/v5/plugin.go#L53

**Comment by johntaiii** [comment]
thanks a lot!
