### ISSUE TITLE
net/rpc可以用于调用运行时间较长的方法吗？

### ISSUE THREAD

**Issue by kaixinbuyu** [henrylee2cn/teleport#42]
基于net/rpc，客户端调用服务端的方法可能运行在小时级别，这种方式可以用吗？
我看到的大部分例子一般都是ms级的方法调用。
还是需要复杂的有心跳，重连等机制的框架？

**Comment by henrylee2cn** [comment]
如果你用net/rpc，不使用心跳，都能运行小时级别的。那么你用tp，不使用心跳插件，同样没问题。

**Comment by henrylee2cn** [comment]
如果你想用心跳，增加通信的可靠性，可以使用 https://github.com/henrylee2cn/teleport/tree/v5/plugin/heartbeat

重连机制是框架内自动实现的，只需配置Config对象的 RedialTimes、RedialInterval 字段

具体特性，可以看readme 
https://github.com/henrylee2cn/teleport/blob/v5/README_ZH.md#%E7%89%B9%E6%80%A7

**Comment by kaixinbuyu** [comment]
感谢，我试一下！
