### ISSUE TITLE
如何保存会话状态？

### ISSUE THREAD

**Issue by chenqinghe** [henrylee2cn/teleport#44]
貌似框架对会话的状态的管理不太友好啊。每次请求过来之后，都会路由到不同的handler实例，这样就不能通过handler来管理会话状态了，得要自己再重新封装一层。后面这块会考虑重构吗？

**Comment by henrylee2cn** [comment]
不需要封装，本来就提供了会话管理的。`sess:=ctx.Session()` 可以获取当前会话。如果需要在当前会话存储一下信息，用 `sess.Swap().Store(k,v)`
