### ISSUE TITLE
handler处理panic了

### ISSUE THREAD

**Issue by chenqinghe** [henrylee2cn/teleport#45]
这里是大致的实现：

> https://gist.github.com/chenqinghe/cadea0fc76f545154204b4dab35a4bef

panic信息：

> [2019/03/16 22:40:01.223] [PRIN] The current process PID: 2884
[2019/03/16 22:40:01.232] [PRIN] register CALL handler: /user/login
[2019/03/16 22:40:01.241] [PRIN] listen and serve (network:tcp, addr:[::]:9090)
[2019/03/16 22:40:12.296] [INFO] accept ok (network:tcp, addr:127.0.0.1:2964, id:127.0.0.1:2964)
[2019/03/16 22:40:12.297] [DEBU] panic:runtime error: invalid memory address or nil pointer dereference
........../server/manager.(*Manager).Add(0x0, 0x0, 0x0, 0xc000194080)
        ........../server/manager/manager.go:21 +0x2d
........../server/handler.(*User).Login(0xc000194000, 0xc00016b260, 0x0, 0x0, 0x0)
        ........../server/handler/user.go:20 +0x12b
reflect.Value.call(0xc0001608a0, 0xc000098528, 0x13, 0x8da74a, 0x4, 0xc00017bd80, 0x2, 0x2, 0x0, 0xc000192180, ...)
        C:/Go/src/reflect/value.go:447 +0x450
reflect.Value.Call(0xc0001608a0, 0xc000098528, 0x13, 0xc00017bd80, 0x2, 0x2, 0x0, 0x0, 0xc00017bdb0)
        C:/Go/src/reflect/value.go:308 +0xab
........../vendor/github.com/henrylee2cn/teleport.makeCallHandlersFromStruct.func2(0xc0000cd810, 0x8261c0, 0xc00016b260, 0x16)
        ........../vendor/github.com/henrylee2cn/teleport/router.go:506 +0x138
........../vendor/github.com/henrylee2cn/teleport.(*handlerCtx).handleCall(0xc0000cd810)
        ........../vendor/github.com/henrylee2cn/teleport/context.go:513 +0x391
........../vendor/github.com/henrylee2cn/teleport.(*handlerCtx).handle(0xc0000cd810)
        ........../vendor/github.com/henrylee2cn/teleport/context.go:366 +0x35f

初步猜测可能是反射复制Manager实例的时候漏了mux字段导致。具体原因暂不详。

**Comment by henrylee2cn** [comment]
注册handler时，赋值是没有意义的。

 `srv.RouteCall(&User{Manager: linkManager})`

因为每次执行handler都是new一个新对象

https://gist.github.com/chenqinghe/cadea0fc76f545154204b4dab35a4bef#file-main-go-L25
