### ISSUE TITLE
关于sequence length

### ISSUE THREAD

**Issue by akuan** [henrylee2cn/teleport#46]
在说明文档中，sequence length是2bytes；
{2 bytes sequence length}
{sequence}

但在文件github.com/henrylee2cn/teleport/socket/protocol.go中sequence length是1bytes；
{1 bytes sequence length}
{sequence}
{1 byte message type} # e.g. CALL:1; REPLY:2; PUSH:3
{1 bytes service method length}
请问是以谁为准呢？还想请教一下seq的编码解码是怎么计算的呢.

**Comment by henrylee2cn** [comment]
文档的是旧的，我已经更新了，具体这是这样，1 byte

```
# raw protocol format(Big Endian):

{4 bytes message length}
{1 byte protocol version}
{1 byte transfer pipe length}
{transfer pipe IDs}
# The following is handled data by transfer pipe
{1 bytes sequence length}
{sequence}
{1 byte message type} # e.g. CALL:1; REPLY:2; PUSH:3
{1 bytes service method length}
{service method}
{2 bytes metadata length}
{metadata(urlencoded)}
{1 byte body codec id}
{body}
```
