### ISSUE TITLE
运行example/Simple失败：qtls.ConnectionState not compatible with tls.ConnectionState

### ISSUE THREAD

**Issue by ourcolour** [henrylee2cn/teleport#47]
运行Simple例子失败，
Win7 64bits
---

panic: qtls.ConnectionState not compatible with tls.ConnectionState

goroutine 1 [running]:
github.com/ourcolour/xnettools/vendor/github.com/lucas-clemente/quic-go/internal/handshake.init.0()
	E:/goprojects/src/github.com/ourcolour/xnettools/vendor/github.com/lucas-clemente/quic-go/internal/handshake/unsafe.go:17 +0x2b3

---

**Comment by henrylee2cn** [comment]
报错原因：两个项目teleport和xnettools都在各自vendor中加了了quic-go，导致类型不一致。
解决办法：在你的项目下添加一个vendor

**Comment by ourcolour** [comment]
`
cd $PROJ_DIR

;; 初始化（如需）
glide init

glide get github.com/lucas-clemente/quic-go
glide get github.com/henrylee2cn/teleport

glide install
`
