### ISSUE TITLE
粘包、半包处理机制

### ISSUE THREAD

**Issue by TaijiGao** [henrylee2cn/teleport#49]
socket读取部分没找到如何处理粘包、半包问题的逻辑

**Comment by leaout** [comment]
我也没找到，这个不能用

**Comment by henrylee2cn** [comment]
这个属于通信协议模块，在proto中，每类协议在设计时都有避免粘包和半包

**Comment by TaijiGao** [comment]
unc (r *rawProto) Unpack(m *Message) error {
	bb := utils.AcquireByteBuffer()
	defer utils.ReleaseByteBuffer(bb)

	// read message
	err := r.readMessage(bb, m)
	if err != nil {
		return err
	}
	// do transfer pipe
	data, err := m.XferPipe().OnUnpack(bb.B)
	if err != nil {
		return err
	}
	// header
	data = r.readHeader(data, m)
	// body
	return r.readBody(data, m)
作者你好，在这个readmessage中，如果bb包含了另外一包的head，或者包含了两包，这个粘包处理的逻辑在哪里？仔细阅读了下代码，bb处理完一个消息，就直接放到pool中了，并没有找到处理连续包或者一个半包这种情况的处理逻辑

**Comment by TaijiGao** [comment]
续上一个问题，在readmessage中，多次连续读几个字节，应该会有性能影响，能否考虑从socket连接读取的内容放到一个大的内存切片，工作协程直接去解析内存切片的内容？

**Comment by leaout** [comment]
寻找包头(包头错误丢掉一字节(循环))->读取一条完整消息->解包 ，好像没有这个逻辑。

**Comment by henrylee2cn** [comment]
```
{4 bytes message length}
{1 byte protocol version}
{1 byte transfer pipe length}
{transfer pipe IDs}
# The following is handled data by transfer pipe
{1 bytes sequence length}
{sequence (HEX 36 string of int32)}
{1 byte message type} # e.g. CALL:1; REPLY:2; PUSH:3
{1 bytes service method length}
{service method}
{2 bytes metadata length}
{metadata(urlencoded)}
{1 byte body codec id}
{body}
```

**Comment by henrylee2cn** [comment]
抱歉没有你想要的这个逻辑，你可以自己实现一个协议，参考已有的协议

leaout <notifications@github.com> 于2019年4月19日周五 上午10:54写道：

**Comment by henrylee2cn** [comment]
> 寻找包头(包头错误丢掉一字节(循环))->读取一条完整消息->解包 ，好像没有这个逻辑。

这类是采用分隔符避免粘包的协议，自带协议中没有提供这一种，你可以通过 Proto 接口自行实现一个。
