### ISSUE TITLE
如何在自定义的 protocol 中在进行 Unpack 和 Pack 的时候获取 session ？

### ISSUE THREAD

**Issue by freeznet** [henrylee2cn/teleport#54]
想自行实现一个 protocol ，但是发现 Unpack 中传递的 Message 并不包含 session 相关的信息，需要依据 session swap 中定义的 key 来对封包进行加解密

**Comment by henrylee2cn** [comment]
不支持，你应该使用plugin来实现扩展功能

**Comment by henrylee2cn** [comment]
这里是一个通用的加解密插件，你可以参考：
https://github.com/henrylee2cn/teleport/tree/v5/plugin/secure

**Comment by freeznet** [comment]
参考了下secure这个插件，但是解密是在readHeader之后做的，我们现在的应用场景需要在readHeader之前对数据进行解密，然后才能解析出header和body，那么这种情况下应该怎么处理呢？谢谢～

**Comment by freeznet** [comment]
看了下感觉XferPipe可以使用，但是不太清楚如何将session swap传入XferPipe中

**Comment by henrylee2cn** [comment]
在Message中可以读写XferPipe
