### ISSUE TITLE
teleport中peer断开连接的处理

### ISSUE THREAD

**Issue by johnnyeven** [henrylee2cn/teleport#62]
想请问一下，在teleport中对于远端连接断开时的错误捕获是怎么进行的，有示例吗？

**Comment by henrylee2cn** [comment]
- 使用事件通知 <-sess.CloseNotify()
- 定义事件回调插件 PostDisconnectPlugin https://github.com/henrylee2cn/teleport/blob/master/plugin.go#L142

**Comment by johnnyeven** [comment]
非常感谢
